---
title: "Trabajo grupal de Estadística Computacional"
author: "Grupo 3: Gerardo Tirado García, Carlos Romero Cruz e Irene Trigueros Lorca"
date: "`r format(Sys.Date(), format='%d de %B del %Y')`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Trabajo grupal de Estadística Computacional}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introducción

## Problema específico
A continuación se va a presentar un problema de uso de los paquetes *snow* y *Rmpi*.

Supongamos que nos encontramos a finales de año, donde la mayoría de empresas y
administraciones analizan su actividad realizada durante el año. En estos análisis se
calculan indicadores estadísticos que permitan representar resúmenes y cualidades de los
resultados obtenidos. Estos procesos cobran significada importancia en el ámbito
hospitalario. 

Los indicadores estadísticos no solo miden el rendimiento de los trabajadores en una 
organización, sino que en ámbitos como el sanitario permiten monitorizar las actividades,
resultados y listas de espera de un hospital o todo un sistema sanitario. Cabe destacar
que, aunque estos datos estadísticos se calculan continuamente, incluso en tiempo real o
en un período de pocos días, sí es cierto que a final del período de curso de actividad
se suelen agrupar para realizar un análisis extenso y exploratorio de un gran conjunto
de centros sanitarios, como el Sistema Andaluz de Salud.

Por este motivo, es posible que en esos períodos sea necesario calcular ciertos parámetros
en cada centro y enviarlos al nodo desde donde puedan ser accedidos por un departamento administrativo general para, posteriormente, aplicar más cálculos o agruparlos
de manera que puedan ser analizados más fácilmente desde diferentes vistas. Así, es un
requerimiento que los datos
que se obtienen de los centros sean calculados homogéneamente, evitando incoherencias o
faltas de integridad. Esta homogeneidad en los cálculos se puede obtener mediante una 
red de computación, donde se puede distribuir el trabajo entre diferentes nodos configurados
y conectados a esta red. Es más, normalmente estos nodos no tienen por qué tener capacidades
o ser homogéneos entre sí. Podrían tratarse de ordenadores o servidores con distintos
sistemas operativos, características *hardware* completamente distintas o incluso ser 
virtuales, dependiendo de cada centro sanitario.

## Paquetes y funciones que permiten resolver el problema


## Ejemplo 1:

## Ejemplo 2:

## Ejemplo 3: